version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - task2-api-vol:/app
    command: python main.py
    env_file: ./api/api.env

  fe:
    build:
      context: ./fe
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file: ./fe/.env

volumes:
  task2-api-vol: